name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Use Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: git
        run: git config --global url.https://${{ secrets.SELEFRA_TOKEN }}@github.com/.insteadOf https://github.com/
      # - run: |
      #     #go run docs/doc_gen.go
      #   env:
      #     SELEFRA_DOC_OUTPUT_DIRECTORY: ./docs
      # - run: |
      #     #ls -la ./docs
